name: CI

on:
  schedule:
    - cron: "50 1 * * 1"
  workflow_dispatch:

jobs:
  update:
    name: Upgrade hook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - run: pip install -r requirements.txt
      - run: git config user.name 'Github Actions'
      - run: git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - run: python3 .github/workflows/update_tags.py
      - run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}
          for tag in $(git tag); do
            git push origin $tag
          done
          git push origin HEAD:refs/heads/main
        # for-loop is required to trigger CI on the tags
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
